name = "reactive_signal"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A Gleam library for cross-process reactive signal"
licences = ["MIT"]
repository = { type = "github", user = "yukikurage", repo = "reactive_signal" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_otp = "~> 0.10"
gleam_erlang = "~> 0.24"

[dev-dependencies]
gleeunit = "~> 1.0"
